name: CD

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push User Service
      uses: docker/build-push-action@v3
      with:
        context: ./services/user-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/church-mgmt-user-service:latest

    # Add similar steps for other services

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        export KUBECONFIG=./kubeconfig
        kubectl apply -f infrastructure/k8s/
